# Generated by Django 5.2.14 on 2026-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionDestinatarios',
            fields=[
                ('evento', models.CharField(choices=[('corte_generado', 'Corte generado'), ('corte_regenerado', 'Corte regenerado'), ('sin_maestro_detectado', 'Producto sin maestra detectado')], max_length=50, primary_key=True, serialize=False)),
                ('correos', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destinatario de notificación',
                'verbose_name_plural': 'Destinatarios de notificación',
            },
        ),
        migrations.CreateModel(
            name='ParametroSalida',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Parámetro de salida',
                'verbose_name_plural': 'Parámetros de salida',
            },
        ),
        migrations.CreateModel(
            name='ReglaClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('campo_destino', models.CharField(choices=[('clasificador1', 'Clasificador 1 (Embalaje)'), ('observaciones', 'Observaciones (Prioridad)')], max_length=20)),
                ('valor_por_defecto', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Regla de clasificación',
                'verbose_name_plural': 'Reglas de clasificación',
                'ordering': ['prioridad'],
            },
        ),
    ]
