# Generated by Django 5.2.14 on 2026-06-01 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('formato_origen', models.CharField(default='PLANTILLA', max_length=20)),
                ('hash_sha256', models.CharField(db_index=True, max_length=64)),
                ('fecha', models.DateField(db_index=True)),
                ('numero_corte', models.PositiveSmallIntegerField(choices=[(1, 'Corte 1'), (2, 'Corte 2'), (3, 'Corte 3 (adicional)')])),
                ('estado', models.CharField(choices=[('cargado', 'Cargado'), ('en_revision', 'En revisión'), ('generado', 'Generado'), ('con_error', 'Con error')], db_index=True, default='cargado', max_length=20)),
                ('version_actual', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_bloqueados', to=settings.AUTH_USER_MODEL)),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-numero_corte'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=30)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('clasificador1', models.CharField(default='EMBALAR', max_length=20)),
                ('observaciones', models.CharField(default='NO PRIORIDAD', max_length=20)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.ciudad')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cortes.corte')),
                ('creado_por_split_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_hijos', to='cortes.documento')),
            ],
            options={
                'ordering': ['factura'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('cantidad_origen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_unidades', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sin_maestro', models.BooleanField(db_index=True, default=False)),
                ('inactivo', models.BooleanField(default=False)),
                ('referencia_snapshot', models.CharField(max_length=50)),
                ('descripcion_snapshot', models.CharField(max_length=200)),
                ('unidad_empaque_snapshot', models.PositiveIntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='cortes.documento')),
                ('movida_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_movidas_a_otros', to='cortes.documento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objeto_tipo', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(max_length=50)),
                ('campo', models.CharField(blank=True, max_length=50)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('tipo_evento', models.CharField(choices=[('edicion', 'Edición'), ('regeneracion', 'Regeneración'), ('split', 'Split de documento'), ('deshacer_split', 'Deshacer split'), ('forzar_liberacion', 'Forzar liberación'), ('creacion', 'Creación'), ('inactivacion', 'Inactivación')], max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['objeto_tipo', 'objeto_id'], name='cortes_audi_objeto__811fbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('drive_url', models.URLField(blank=True)),
                ('archivo_hash', models.CharField(max_length=64)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='cortes.corte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['corte', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('corte', 'numero'), name='uq_corte_version')],
            },
        ),
    ]
