# Generated by Django 5.2.14 on 2026-06-01 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_evento',
            field=models.CharField(choices=[('edicion', 'Edición'), ('regeneracion', 'Regeneración'), ('split', 'Split de documento'), ('deshacer_split', 'Deshacer split'), ('forzar_liberacion', 'Forzar liberación'), ('creacion', 'Creación'), ('inactivacion', 'Inactivación'), ('login_fallido', 'Login fallido'), ('notificacion_fallida', 'Notificación fallida')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
