# Generated by Django 5.2.14 on 2026-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0002_add_metadata_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='factura_sufijo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='subsanar_novedad',
            field=models.BooleanField(default=False),
        ),
    ]
