# Generated by Django 5.2.14 on 2026-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0006_corte_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corte',
            options={'ordering': ['-fecha', 'numero_corte', 'adicional_letra']},
        ),
        migrations.AlterField(
            model_name='documento',
            name='observaciones',
            field=models.CharField(default='PRIORIDAD', max_length=20),
        ),
        migrations.RunSQL(
            "UPDATE cortes_linea SET cantidad_unidades = ROUND(cantidad_unidades)",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='linea',
            name='cantidad_unidades',
            field=models.PositiveIntegerField(),
        ),
    ]
