# Generated by Django 5.2.14 on 2026-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0007_cantidad_unidades_entero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corte',
            name='tipo_comprobante',
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_comprobante',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
