# Generated by Django 5.2.14 on 2026-07-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cortes', '0008_documento_tipo_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='sucursal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
