# Generated by Django 5.2.14 on 2026-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0009_documento_cliente_documento_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='punto_incluido',
            field=models.BooleanField(default=False),
        ),
    ]
