# Generated by Django 5.2.14 on 2026-09-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes', '0011_corte_estado_actualizado_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_evento',
            field=models.CharField(choices=[('edicion', 'Edición'), ('regeneracion', 'Regeneración'), ('split', 'Split de documento'), ('deshacer_split', 'Deshacer split'), ('eliminacion', 'Eliminación'), ('forzar_liberacion', 'Forzar liberación'), ('creacion', 'Creación'), ('inactivacion', 'Inactivación'), ('login_fallido', 'Login fallido'), ('notificacion_fallida', 'Notificación fallida')], max_length=30),
        ),
    ]
