# Generated by Django 5.2.14 on 2026-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad_empaque', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('revisado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['referencia'],
            },
        ),
    ]
