# Generated by Django 5.2.14 on 2026-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_ciudad_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'revisado'], name='productos_p_activo_022e7f_idx'),
        ),
    ]
