# Generated by Django 5.2.14 on 2026-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sucursal', models.CharField(blank=True, max_length=20)),
                ('dv', models.CharField(blank=True, max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=5)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('telefono_1', models.CharField(blank=True, max_length=20)),
                ('telefono_2', models.CharField(blank=True, max_length=20)),
                ('telefono_3', models.CharField(blank=True, max_length=20)),
                ('telefono_4', models.CharField(blank=True, max_length=20)),
                ('apartado', models.CharField(blank=True, max_length=20)),
                ('clasificacion', models.CharField(blank=True, max_length=50)),
                ('forma_pago', models.CharField(blank=True, max_length=20)),
                ('dia', models.CharField(blank=True, max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
