# Generated by Django 5.2.17 on 2026-10-06 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones_siigo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('tomada', 'Tomada'), ('completada', 'Completada'), ('fallida', 'Fallida')], db_index=True, default='pendiente', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('tomada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('extraction_id', models.UUIDField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de extracción',
                'verbose_name_plural': 'Solicitudes de extracción',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='ingestionsiigo',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestiones', to='integraciones_siigo.solicitudextraccion'),
        ),
        migrations.CreateModel(
            name='FilaSiigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(max_length=5)),
                ('codigo_comprobante', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=30)),
                ('secuencia', models.CharField(max_length=20)),
                ('fecha_documento', models.DateField(db_index=True)),
                ('fila', models.JSONField()),
                ('no_presente_en_siigo', models.BooleanField(default=False)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_siigo', to='integraciones_siigo.ingestionsiigo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo_comprobante', 'codigo_comprobante', 'numero_documento', 'secuencia'), name='fila_siigo_unica')],
            },
        ),
    ]
