# Generated by Django 5.2.17 on 2026-10-06 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones_siigo', '0002_solicitudes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solicitudextraccion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'tomada'])), fields=('fecha_inicio', 'fecha_fin'), name='solicitud_en_curso_unica'),
        ),
    ]
